version: "3"
services:
  client:
    image: atnu/soundscapes-client
    build:
      context: ./
      dockerfile: client/Dockerfile
    ports:
      - "4100:80"
    networks:
      - soundscapes
  server:
    image: atnu/soundscapes-server
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - "4200:8080"
    networks:
      - soundscapes

networks:
  soundscapes: