version: "3"
services:
  client:
    image: atnu/soundscapes-client
    build:
      context: ./
      dockerfile: client/Dockerfile
    ports:
      - "4100:80"
    networks:
      - soundscapes
  server:
    image: atnu/soundscapes-server
    environment:
        # - AWS_DEFAULT_REGION=${REGION}
        # - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        # - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=eu-west-1
        - AWS_ACCESS_KEY_ID=AKIAJVRS2TYVUQZINKJQ
        - AWS_SECRET_ACCESS_KEY=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
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - "4300:8080"
    networks:
      - soundscapes

networks:
  soundscapes:
