version: "3"
services:
  client:
    image: atnu/soundscapes-client
    build:
      context: ./
      dockerfile: client/Dockerfile
    ports:
      - "4100:80"
    networks:
      - soundscapes
  server:
    image: atnu/soundscapes-server
    environment:
        - AWS_DEFAULT_REGION=${region}
        - AWS_ACCESS_KEY_ID=${aws_access_key_id}
        - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
    build:
      context: ./
      dockerfile: server/Dockerfile
    ports:
      - "4200:8080"
    networks:
      - soundscapes

networks:
  soundscapes:
