version: 2.0

jobs:
  build-server:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/ATNU/soundscapes-of-text/server

    steps:
      - checkout:
          path: /go/src/github.com/ATNU/soundscapes-of-text

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get github.com/spf13/viper
      - run: go get github.com/gorilla/mux
      - run: go get github.com/fsnotify/fsnotify
      - run: go get github.com/aws/aws-sdk-go/aws/session
      - run: go get github.com/aws/aws-sdk-go/service/polly
      - run: go get github.com/aws/aws-sdk-go/aws
      - run: go get github.com/aws/aws-sdk-go/service/polly/pollyiface

      - run: CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o app .

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
workflows:
  version: 2
  untagged-build:
    jobs:
      - build-server

